 # Maven
 # Build your Java project and run tests with Apache Maven.
 # Add steps that analyze code, save build artifacts, deploy, and more:
 # https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  appName: 'my-spring-app123'

pool:
  name: Default

steps:
- script: mvn clean package
  displayName: Build with Maven

#Step 2: Copy JAR to staging folder
- task: CopyFiles@2
  displayName: Copy JAR to artifact staging directory
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Step 3: Deploy to Azure Web App
- task: AzureWebApp@1
  displayName: Deploy to Azure Web App
  inputs:
    azureSubscription: 'Rounak-007'
    appName: '$(appName)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.jar'

